#if !canImport(ObjectiveC)
import XCTest

extension LogLevelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogLevelTests = [
        ("testDebug", testDebug),
        ("testError", testError),
        ("testInfo", testInfo),
        ("testTrace", testTrace),
        ("testWarn", testWarn),
    ]
}

extension SimpleLoggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimpleLoggerTests = [
        ("testCreateLogger", testCreateLogger),
    ]
}

extension StringPaddingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringPaddingTests = [
        ("testPaddingLeftWhenEqualToLength", testPaddingLeftWhenEqualToLength),
        ("testPaddingLeftWhenLongerThenLength", testPaddingLeftWhenLongerThenLength),
        ("testPaddingLeftWhenShorterThenLength", testPaddingLeftWhenShorterThenLength),
        ("testPaddingRightWhenEqualToLength", testPaddingRightWhenEqualToLength),
        ("testPaddingRightWhenLongerThenLength", testPaddingRightWhenLongerThenLength),
        ("testPaddingRightWhenShorterThenLength", testPaddingRightWhenShorterThenLength),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LogLevelTests.__allTests__LogLevelTests),
        testCase(SimpleLoggerTests.__allTests__SimpleLoggerTests),
        testCase(StringPaddingTests.__allTests__StringPaddingTests),
    ]
}
#endif
